// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lab2;

namespace lab2.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210312142357_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("lab2.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("Flat")
                        .HasColumnType("integer");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<int>("House")
                        .HasColumnType("integer");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankAccountNumber = "32784872371",
                            BirthDate = new DateTime(1990, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Minsk",
                            Country = "Belarus",
                            CreditCardNumber = "byt23473hfw73",
                            District = "Minsky",
                            FirstName = "Ivan",
                            Flat = 117,
                            Gender = true,
                            Height = 1.8,
                            House = 23,
                            Nationality = "Belarusian",
                            PhoneNumber = "375291234567",
                            Postcode = "220076",
                            Region = "Minsky",
                            SecondName = "Ivanovich",
                            Street = "Slobodskaya",
                            Surname = "Ivanov",
                            Weight = 79.5
                        },
                        new
                        {
                            Id = 2,
                            BankAccountNumber = "12874981209",
                            BirthDate = new DateTime(1987, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brest",
                            Country = "Belarus",
                            CreditCardNumber = "zdr69365ysl15",
                            District = "Brestsky",
                            FirstName = "Petr",
                            Flat = 2,
                            Gender = true,
                            Height = 1.6699999999999999,
                            House = 15,
                            Nationality = "Belarusian",
                            PhoneNumber = "375447851287",
                            Postcode = "220076",
                            Region = "Brestsky",
                            SecondName = "Petrovich",
                            Street = "Pushkina",
                            Surname = "Petrov",
                            Weight = 65.299999999999997
                        },
                        new
                        {
                            Id = 3,
                            BankAccountNumber = "41409212945",
                            BirthDate = new DateTime(2003, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Minsk",
                            Country = "Belarus",
                            CreditCardNumber = "top63398orp16",
                            District = "Minsky",
                            FirstName = "Anna",
                            Flat = 213,
                            Gender = false,
                            Height = 1.6499999999999999,
                            House = 7,
                            Nationality = "Belarusian",
                            PhoneNumber = "375298365509",
                            Postcode = "220076",
                            Region = "Minsky",
                            SecondName = "Ivanovna",
                            Street = "Pobedy square",
                            Surname = "Ivanova",
                            Weight = 89.099999999999994
                        },
                        new
                        {
                            Id = 4,
                            BankAccountNumber = "22973076899",
                            BirthDate = new DateTime(1997, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gomel",
                            Country = "Belarus",
                            CreditCardNumber = "iiu89017zzk22",
                            District = "Gomelsky",
                            FirstName = "Miron",
                            Flat = 23,
                            Gender = true,
                            Height = 1.8,
                            House = 4,
                            Nationality = "Belarusian",
                            PhoneNumber = "375338175098",
                            Postcode = "220076",
                            Region = "Gomelsky",
                            SecondName = "Semenovich",
                            Street = "Dzerzhinskogo",
                            Surname = "Smirnov",
                            Weight = 89.219999999999999
                        },
                        new
                        {
                            Id = 5,
                            BankAccountNumber = "16329993456",
                            BirthDate = new DateTime(1995, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Soligorsk",
                            Country = "Belarus",
                            CreditCardNumber = "wer46709odk92",
                            District = "Soligorsky",
                            FirstName = "Vladimir",
                            Flat = 55,
                            Gender = true,
                            Height = 1.8899999999999999,
                            House = 81,
                            Nationality = "Belarusian",
                            PhoneNumber = "375292340987",
                            Postcode = "220076",
                            Region = "Minsky",
                            SecondName = "Igorevich",
                            Street = "Lenina",
                            Surname = "Kotov",
                            Weight = 100.3
                        },
                        new
                        {
                            Id = 6,
                            BankAccountNumber = "27382991203",
                            BirthDate = new DateTime(2000, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brest",
                            Country = "Belarus",
                            CreditCardNumber = "byi32784lao63",
                            District = "Brestsky",
                            FirstName = "Maria",
                            Flat = 64,
                            Gender = false,
                            Height = 1.6499999999999999,
                            House = 17,
                            Nationality = "Belarusian",
                            PhoneNumber = "375445679876",
                            Postcode = "220076",
                            Region = "Brestsky",
                            SecondName = "Mihailovna",
                            Street = "Volodarskogo",
                            Surname = "Petrova",
                            Weight = 59.0
                        },
                        new
                        {
                            Id = 7,
                            BankAccountNumber = "34729502493",
                            BirthDate = new DateTime(1984, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brest",
                            Country = "Belarus",
                            CreditCardNumber = "off11874oqi81",
                            District = "Brestsky",
                            FirstName = "Svetlana",
                            Flat = 87,
                            Gender = false,
                            Height = 1.71,
                            House = 22,
                            Nationality = "Belarusian",
                            PhoneNumber = "375291718190",
                            Postcode = "220076",
                            Region = "Brestsky",
                            SecondName = "Stepanovna",
                            Street = "Morozova",
                            Surname = "Smirnova",
                            Weight = 71.299999999999997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
