// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lab2;

namespace lab2.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("lab2.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("bank_account_number")
                        .HasColumnType("text");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<string>("credit_card_number")
                        .HasColumnType("text");

                    b.Property<string>("district")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<int?>("flat")
                        .HasColumnType("integer");

                    b.Property<bool>("gender")
                        .HasColumnType("boolean");

                    b.Property<double>("height")
                        .HasColumnType("double precision");

                    b.Property<int>("house")
                        .HasColumnType("integer");

                    b.Property<string>("nationality")
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("postcode")
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .HasColumnType("text");

                    b.Property<string>("second_name")
                        .HasColumnType("text");

                    b.Property<string>("street")
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.Property<double>("weight")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("customer");

                    b.HasData(
                        new
                        {
                            id = 1,
                            bank_account_number = "32784872371",
                            birth_date = new DateTime(1990, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Minsk",
                            country = "Belarus",
                            credit_card_number = "byt23473hfw73",
                            district = "Minsky",
                            first_name = "Ivan",
                            flat = 117,
                            gender = true,
                            height = 1.8,
                            house = 23,
                            nationality = "Belarusian",
                            phone_number = "375291234567",
                            postcode = "220076",
                            region = "Minsky",
                            second_name = "Ivanovich",
                            street = "Slobodskaya",
                            surname = "Ivanov",
                            weight = 79.5
                        },
                        new
                        {
                            id = 2,
                            bank_account_number = "12874981209",
                            birth_date = new DateTime(1987, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Brest",
                            country = "Belarus",
                            credit_card_number = "zdr69365ysl15",
                            district = "Brestsky",
                            first_name = "Petr",
                            flat = 2,
                            gender = true,
                            height = 1.6699999999999999,
                            house = 15,
                            nationality = "Belarusian",
                            phone_number = "375447851287",
                            postcode = "220076",
                            region = "Brestsky",
                            second_name = "Petrovich",
                            street = "Pushkina",
                            surname = "Petrov",
                            weight = 65.299999999999997
                        },
                        new
                        {
                            id = 3,
                            bank_account_number = "41409212945",
                            birth_date = new DateTime(2003, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Minsk",
                            country = "Belarus",
                            credit_card_number = "top63398orp16",
                            district = "Minsky",
                            first_name = "Anna",
                            flat = 213,
                            gender = false,
                            height = 1.6499999999999999,
                            house = 7,
                            nationality = "Belarusian",
                            phone_number = "375298365509",
                            postcode = "220076",
                            region = "Minsky",
                            second_name = "Ivanovna",
                            street = "Pobedy square",
                            surname = "Ivanova",
                            weight = 89.099999999999994
                        },
                        new
                        {
                            id = 4,
                            bank_account_number = "22973076899",
                            birth_date = new DateTime(1997, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Gomel",
                            country = "Belarus",
                            credit_card_number = "iiu89017zzk22",
                            district = "Gomelsky",
                            first_name = "Miron",
                            flat = 23,
                            gender = true,
                            height = 1.8,
                            house = 4,
                            nationality = "Belarusian",
                            phone_number = "375338175098",
                            postcode = "220076",
                            region = "Gomelsky",
                            second_name = "Semenovich",
                            street = "Dzerzhinskogo",
                            surname = "Smirnov",
                            weight = 89.219999999999999
                        },
                        new
                        {
                            id = 5,
                            bank_account_number = "16329993456",
                            birth_date = new DateTime(1995, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Soligorsk",
                            country = "Belarus",
                            credit_card_number = "wer46709odk92",
                            district = "Soligorsky",
                            first_name = "Vladimir",
                            flat = 55,
                            gender = true,
                            height = 1.8899999999999999,
                            house = 81,
                            nationality = "Belarusian",
                            phone_number = "375292340987",
                            postcode = "220076",
                            region = "Minsky",
                            second_name = "Igorevich",
                            street = "Lenina",
                            surname = "Kotov",
                            weight = 100.3
                        },
                        new
                        {
                            id = 6,
                            bank_account_number = "27382991203",
                            birth_date = new DateTime(2000, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Brest",
                            country = "Belarus",
                            credit_card_number = "byi32784lao63",
                            district = "Brestsky",
                            first_name = "Maria",
                            flat = 64,
                            gender = false,
                            height = 1.6499999999999999,
                            house = 17,
                            nationality = "Belarusian",
                            phone_number = "375445679876",
                            postcode = "220076",
                            region = "Brestsky",
                            second_name = "Mihailovna",
                            street = "Volodarskogo",
                            surname = "Petrova",
                            weight = 59.0
                        },
                        new
                        {
                            id = 7,
                            bank_account_number = "34729502493",
                            birth_date = new DateTime(1984, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            city = "Brest",
                            country = "Belarus",
                            credit_card_number = "off11874oqi81",
                            district = "Brestsky",
                            first_name = "Svetlana",
                            flat = 87,
                            gender = false,
                            height = 1.71,
                            house = 22,
                            nationality = "Belarusian",
                            phone_number = "375291718190",
                            postcode = "220076",
                            region = "Brestsky",
                            second_name = "Stepanovna",
                            street = "Morozova",
                            surname = "Smirnova",
                            weight = 71.299999999999997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
